version: '2'
  services:
    web:
      build: .
      ports:
        - "3001:3001"
      environment:
        NODE_ENV: 'docker'
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'root'
        MYSQL_ROOT_PASSWORD: 'root'
      depends_on:
        - db
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'root'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3306:3306'
      volumes:
      # - ./migration/mysql:/docker-entrypoint-initdb.d
      # - ./mysql-volume:/var/lib/mysql
