version: '2'
services:
    web:
      build: .
      ports:
        - "3000:3000"
      environment:
        NODE_ENV: 'production'
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'root'
        MYSQL_ROOT_PASSWORD: 'root'
      depends_on:
        - db
    db:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'root'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3307:3307'
